### ISSUE TITLE
Sample unity project

### ISSUE THREAD

**Issue by mirzasohailbaig** [stefanak-michal/Unity-FileShare#1]
First off this seems like it could be a efficient way to share files between unity apps but I really don't get how to use this. Is there any way you could add a sample unity project to show how to set it up, I would gladly pay for a nice lunch if you could.

**Comment by stefanak-michal** [comment]
I've hope this will help. It's assets from sample project created in Unity 5.5. Structure is classic NetworkManager with HUD, FileShare script and UI canvas with option to send file.

[Assets.zip](https://github.com/stefanak-michal/Unity-FileShare/files/2088855/Assets.zip)

**Comment by mirzasohailbaig** [comment]
Thanks for the fast reply, as promised I sent some money for lunch. 

So I kept everything the way you sent it and started server in unity (by clicking LAN Server Only) and started as client in Windows build  (by clicking LAN Client (C)). Then I pressed send in Unity game view but it says `NullReferenceException: for this line# 132             NetworkManager.singleton.client.Send(fileSharePrepare, new FileSharePrepare()
` so basically this way fails. 

Since that didn't work, I started it as host in unity (by clicking LAN Host) and started as client in Windows build  (by clicking LAN Client (C)). Then I pressed send in Unity game view and in unity console it printed `"Sending file "C:\Users\xxx\Desktop\xxxx.pdf" through port 47100" ` but it also states in the game view `"received file C:\Users\xxx\AppData\Local\Temp\20180611031720_3114.pdf
" `. So this basically means it sent the file to the server since it is also a client. As a result the Windows build client app never states it received file. But if I press send again in unity, then the windows client build states `"received file C:\Users\xxx\AppData\Local\Temp\20180611032357_2753.pdf
"
"received file C:\Users\xxx\AppData\Local\Temp\20180611032357_2753.pdf
" ` twice.

So am I supposed to be using server app as host because it doesn't seem like this is expected behavior?

**Comment by stefanak-michal** [comment]
I never tried Server only. I'm always using Host. I'll check it, if I can make some update to make it work.

Default behaviour is: the file is sended to all clients who have registered "action". That means, you can unregister that action on client, who is sending that file.

I created the output log to work with append, not replace. If you are sending same file, it's used the old one to save network communication. The script is checking hash of first sended buffer to check this similarity of file. That's the reason why you have two similar messages.

_Thanks for lunch :)_

**Comment by mirzasohailbaig** [comment]
Also it doesn't seem to send/save file if I change it to this: 

           ```
//received files are stored in temp
            string tmpFile =  Path.Combine(Application.persistentDataPath, "/NewScenarios")+ name+ ".tmp";
            string normalFile = Path.Combine(Application.persistentDataPath, "/NewScenarios")+ name + extension;
```

Is there a reason why it can't files to this location ?

**Comment by stefanak-michal** [comment]
File isn't processed in main thread. Unity doesn't like other threads, usually when you try call unity method/function in background thread you get a error. You are using Application.persistentDataPath and that is a problem.

get_persistentDataPath can only be called from the main thread.

If you want to use this path, I recommend to create class private variable, in Start() assign Application.persistentDataPath to this private variable and use it latter.

**Comment by mirzasohailbaig** [comment]
this is how i did it 


    ```
private void Start()
    {
        scenarioDirectory = Path.Combine(Application.persistentDataPath, "/NewScenarios");
#if UNITY_EDITOR
        scenarioDirectory = Path.Combine(Application.dataPath, "/NewScenarios");
#endif
        instance = this;
        r = new System.Random();
        StartCoroutine(RegisterHandlers());
    }
...
//received files are stored in temp
            string tmpFile = scenarioDirectory + name + ".tmp";
            string normalFile = scenarioDirectory + name + extension;
```

this way does not work for me is there a different way ?

**Comment by stefanak-michal** [comment]
I made two updates. First one is solution about server only version. Second is option to set target directory. I add verification of ending char.

**Comment by mirzasohailbaig** [comment]
Awesome! That resolved my directory issue, but when clicking on `LAN Server Only` I get the same null reference. 

` NullReferenceException: for this line# 132 NetworkManager.singleton.client.Send(fileSharePrepare, new FileSharePrepare()`

**Comment by stefanak-michal** [comment]
NullReferenceException on that line means you are putting null into GetCRC() method. What is your filename you are trying to send? Because if you leave the inputField empty and just push button to send file, it makes sense you get this error. If we speak about sample scene.

**Comment by stefanak-michal** [comment]
Ah, I got your error and now I understand :D You are trying to send file from that server, not from client. I will check how to solve it.

**Comment by mirzasohailbaig** [comment]
cool, I thought it was always server->client file transfer. Also is it possible to make the file transfers both ways if needed ? (I'm planning to use this as a bidirectional file backup system)

**Comment by mirzasohailbaig** [comment]
Ok so if I use Host() to start a server and client, then if another client connects() can he send files or can only the host() send files ? ( When I was testing it didn't seem like the second client could send files) 

Also in your opinion is it faster to send one zip file containing

**Comment by mirzasohailbaig** [comment]
Never mind it does work as you stated it client<->client that's good perfect I can probably build around this. 

Thanks a lot for your help, I'll let you know if I have any other issues.

**Comment by stefanak-michal** [comment]
Host is also client and server. Host can send and receive files because is client.
