### ISSUE TITLE
File Sending is only working on From Server->Client

### ISSUE THREAD

**Issue by mirzasohailbaig** [stefanak-michal/Unity-FileShare#2]
My issue is that that if the "Host" app presses "Send file" on a certain file it sends the file to client correctly but if the client presses the "Send file" on a certain it never sends the file.

Details:
I'm using Unity 5.5.0f3 and using the NEW 'assets' folder you provided in 'Issues' I've tested this using 2 separate windows machines.  I've attached my assets folder which is not very different I just specify different directories to save in. 
[Assets.zip](https://github.com/stefanak-michal/Unity-FileShare/files/2162160/Assets.zip)

**Comment by stefanak-michal** [comment]
Please can you use normal source code, not the stuff from closed issue.

That client has registered receive action? 
Can you see messages "fileSharePrepare" and "getClientsSendFile" in unity profiler network messages? (is usually the last profiler row)

**Comment by mirzasohailbaig** [comment]
The client is registered to receive action, and I attached an image of what I see in profiler (i've never used it so don't really understand it). I updated the **fileshare.cs** as instructed.
![test](https://user-images.githubusercontent.com/8581543/42264923-b0ec72fe-7f37-11e8-81b6-92646cd83e3c.png)


=========
Re-Ran Tests:
=========
1. File from [Host]-> [Client]
 Result: PASS, Client receives file as expected. 

1. File from [Client]-> [Host]
Result: FAIL, Host never receives file instead the same client receives the file it sent.

**Comment by mirzasohailbaig** [comment]
here's the client sending file:
====
![client](https://user-images.githubusercontent.com/8581543/42270515-b47252e0-7f46-11e8-86cc-23a630692980.png)

here's the host sending file:
====
![host](https://user-images.githubusercontent.com/8581543/42270568-d2b23608-7f46-11e8-8672-1c4b5c72a1d2.png)

**Comment by stefanak-michal** [comment]
yeah I was thinking about this "network operator" profiler. I never remember which one it is ;)

Do you have some "fileshare.log"? It's created next to exe/project if something happen in background threads.

**Comment by mirzasohailbaig** [comment]
I do have some log when client sends file to host, this log is for Host (client has no log error). 

```
[7/4/2018 5:43:12 AM] System: Only one usage of each socket address (protocol/network address/port) is normally permitted.

  at System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpListener.Start (Int32 backlog) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpListener.Start () [0x00000] in <filename unknown>:0 
```

**Comment by stefanak-michal** [comment]
Maybe this will help you https://github.com/stefanak-michal/Unity-FileShare/commit/cf3fd39618ead0e559c2654655dc789bbce631fb

**Comment by mirzasohailbaig** [comment]
that commit works well, but the other issue is that both (HOST & CLIENT) always sends the file to themselves as well (even if you unsubscribe from receive action) is there anyway to NOT send the file to themselves ? I can't see a reason why you would want to send the same file to yourself in the first place.

**Comment by stefanak-michal** [comment]
Did you try unregister action before send? It works for me.

```csharp
FileShare.UnregisterReceiveAction("sendFile");
FileShare.Send(fileToSend, "sendFile");
```

**Comment by mirzasohailbaig** [comment]
I've tested  `FileShare.UnregisterReceiveAction("sendFile");` it simply prevents `Action<string> action `  from running for function `RegisterReceiveAction(string name, Action <string> action )`, and so it still sends the file to itself.

**Comment by stefanak-michal** [comment]
Yes. It's a problem at this moment? 
It's possible to create some exclude modification, but I don't have time for that right now.

**Comment by mirzasohailbaig** [comment]
I managed to resolve it below are some details about it... 

=======
1. I replaced the `GetIp()` method to simply `Network.player.ipAddress` because `GetIp()` does NOT return local IP it returns something like 772.241.115.xx because the its looking for all IPs on PC.

=======
2. I changed 2 functions such that they  `continue`  when `conn.address` equals `Network.player.ipAddress`.

 ```
  public static void Send(string file, string receiveAction)
    {
       ...
        else if (NetworkServer.active)
        {
            NetworkServer.SendToAll(fileSharePrepare, prepareMsg);
            foreach (var conn in NetworkServer.connections)
            {
                UnityEngine.Debug.Log(conn.address);
                if (Network.player.ipAddress == conn.address.Replace("::ffff:", ""))
                {
                    continue;
                }
                if (conn != null)
                    InvokeThread(conn.address, port, file);
            }
        }
    }
```
```
 private void SendFileToClients(NetworkMessage netMsg)
    {
        NetConn msg = netMsg.ReadMessage<NetConn>();

        foreach (var addr in msg.addresses) {
            if (Network.player.ipAddress == addr.Replace("::ffff:", "")) {
                continue;
            }
                
            InvokeThread(addr, msg.port, msg.file);
        }
    }
```

**Comment by mirzasohailbaig** [comment]
One more question how difficult would it be to make it multi-file transfer? I'm guessing it should be something as simple as keeping the socket open and sending each individual file in a queue until all files are sent but not sure if there's more to it.  Also any plans of implementing this ? **(I'm going to be attempting to integrate this myself but wanted your opinion on it)**

**Comment by stefanak-michal** [comment]
Getting current IP is always a issue. How I wrote to the commit, Unity returning "localClient" instead of IP in situation when you asking on Host side.
You can modify the script however you want. It's opensource ;)

I wasn't thinking about sending queue. You're first who is asking about it. This solution is more about sending some files sometimes. Maybe if you want queue, will be better another approach. At the beginning create a TCP connections between clients and keep them alive. But that is a completely new script. You can use logic/concept from this script and create own one. That logic is also described in wiki.
